
package eu.agileeng.ws.operator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
//@WebService(name = "OperatorWebServiceInterface", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
public interface OperatorWebServiceInterface {


    /**
     * 
     * @param boxId
     * @param text
     * @param rawScan
     * @param serviceId
     * @param virtualBoxId
     * @param improvedFileExtension
     * @param improvedScan
     * @param docId
     * @param rawFileExtension
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendFile")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "SendFile", targetNamespace = "http://service.operator.dematbox.sagemcom.com/", className = "eu.agileeng.ws.operator.SendFile")
    @ResponseWrapper(localName = "SendFileResponse", targetNamespace = "http://service.operator.dematbox.sagemcom.com/", className = "eu.agileeng.ws.operator.SendFileResponse")
    public String sendFile(
        @WebParam(name = "boxId", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        String boxId,
        @WebParam(name = "serviceId", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        int serviceId,
        @WebParam(name = "virtualBoxId", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        String virtualBoxId,
        @WebParam(name = "docId", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        long docId,
        @WebParam(name = "rawScan", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        byte[] rawScan,
        @WebParam(name = "rawFileExtension", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        String rawFileExtension,
        @WebParam(name = "improvedScan", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        byte[] improvedScan,
        @WebParam(name = "improvedFileExtension", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        String improvedFileExtension,
        @WebParam(name = "text", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
        String text);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PingOperator")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.operator.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "PingOperator", targetNamespace = "http://service.operator.dematbox.sagemcom.com/", className = "eu.agileeng.ws.operator.PingOperator")
    @ResponseWrapper(localName = "PingOperatorResponse", targetNamespace = "http://service.operator.dematbox.sagemcom.com/", className = "eu.agileeng.ws.operator.PingOperatorResponse")
    public String pingOperator();

}
