
package eu.agileeng.ws.operator;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
//@WebServiceClient(name = "OperatorWebService", targetNamespace = "http://service.operator.dematbox.sagemcom.com/", wsdlLocation = "file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/operator.wsdl")
public class OperatorWebService
    extends Service
{

    private final static URL OPERATORWEBSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eu.agileeng.ws.operator.OperatorWebService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eu.agileeng.ws.operator.OperatorWebService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/operator.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/operator.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        OPERATORWEBSERVICE_WSDL_LOCATION = url;
    }

    public OperatorWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperatorWebService() {
        super(OPERATORWEBSERVICE_WSDL_LOCATION, new QName("http://service.operator.dematbox.sagemcom.com/", "OperatorWebService"));
    }

    /**
     * 
     * @return
     *     returns OperatorWebServiceInterface
     */
    @WebEndpoint(name = "OperatorWebServicePort")
    public OperatorWebServiceInterface getOperatorWebServicePort() {
        return super.getPort(new QName("http://service.operator.dematbox.sagemcom.com/", "OperatorWebServicePort"), OperatorWebServiceInterface.class);
    }

}
