
package eu.agileeng.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
//@WebService(name = "IWSFrontal", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
public interface IWSFrontal {


    /**
     * 
     * @param operatorId
     * @return
     *     returns eu.agileeng.ws.client.ServiceListBean
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "GetServiceList")
    @WebResult(name = "serviceList", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "GetServiceList", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.GetServiceList")
    @ResponseWrapper(localName = "GetServiceListResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.GetServiceListResponse")
    public ServiceListBean getServiceList(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId)
        throws SoapFaultException
    ;

    /**
     * 
     * @param operatorId
     * @param virtualBoxId
     * @return
     *     returns eu.agileeng.ws.client.SubscribedListBean
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "GetServiceSubscribed")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "GetServiceSubscribed", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.GetServiceSubscribed")
    @ResponseWrapper(localName = "GetServiceSubscribedResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.GetServiceSubscribedResponse")
    public SubscribedListBean getServiceSubscribed(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId,
        @WebParam(name = "virtualBoxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String virtualBoxId)
        throws SoapFaultException
    ;

    /**
     * 
     * @param boxId
     * @param services
     * @param operatorId
     * @param virtualBoxId
     * @param exclusiveness
     * @param localServicesCredit
     * @param pairingCode
     * @param publicIp
     * @param operatorsAuthorized
     * @return
     *     returns java.lang.String
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "ServiceSubscribe")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "ServiceSubscribe", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.ServiceSubscribe")
    @ResponseWrapper(localName = "ServiceSubscribeResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.ServiceSubscribeResponse")
    public String serviceSubscribe(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId,
        @WebParam(name = "virtualBoxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String virtualBoxId,
        @WebParam(name = "boxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String boxId,
        @WebParam(name = "publicIp", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String publicIp,
        @WebParam(name = "localServicesCredit", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int localServicesCredit,
        @WebParam(name = "services", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        ServicesBean services,
        @WebParam(name = "exclusiveness", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        Boolean exclusiveness,
        @WebParam(name = "operatorsAuthorized", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        OperatorAuthBean operatorsAuthorized,
        @WebParam(name = "pairingCode", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String pairingCode)
        throws SoapFaultException
    ;

    /**
     * 
     * @param message
     * @param boxId
     * @param operatorId
     * @param messageDuration
     * @param docId
     * @return
     *     returns java.lang.String
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "UploadNotification")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "UploadNotification", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.UploadNotification")
    @ResponseWrapper(localName = "UploadNotificationResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.UploadNotificationResponse")
    public String uploadNotification(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId,
        @WebParam(name = "boxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String boxId,
        @WebParam(name = "docId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        long docId,
        @WebParam(name = "message", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String message,
        @WebParam(name = "messageDuration", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int messageDuration)
        throws SoapFaultException
    ;

    /**
     * 
     * @param customerName
     * @param services
     * @param operatorId
     * @param virtualBoxId
     * @param localServicesCredit
     * @param exclusiveness
     * @param pairingCode
     * @param publicIp
     * @param operatorsAuthorized
     * @return
     *     returns java.lang.String
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "PutServiceSubscribe")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "PutServiceSubscribe", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.PutServiceSubscribe")
    @ResponseWrapper(localName = "PutServiceSubscribeResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.PutServiceSubscribeResponse")
    public String putServiceSubscribe(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId,
        @WebParam(name = "virtualBoxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String virtualBoxId,
        @WebParam(name = "customerName", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String customerName,
        @WebParam(name = "publicIp", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String publicIp,
        @WebParam(name = "pairingCode", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String pairingCode,
        @WebParam(name = "services", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        ListServiceGroupsBean services,
        @WebParam(name = "exclusiveness", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        Boolean exclusiveness,
        @WebParam(name = "operatorsAuthorized", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        OperatorAuthBean operatorsAuthorized,
        @WebParam(name = "localServicesCredit", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int localServicesCredit)
        throws SoapFaultException
    ;

    /**
     * 
     * @param operatorId
     * @param virtualBoxId
     * @return
     *     returns java.lang.String
     * @throws SoapFaultException
     */
    @WebMethod(operationName = "ServiceUnsubscribe")
    @WebResult(name = "errorReturn", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
    @RequestWrapper(localName = "ServiceUnsubscribe", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.ServiceUnsubscribe")
    @ResponseWrapper(localName = "ServiceUnsubscribeResponse", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/", className = "eu.agileeng.ws.client.ServiceUnsubscribeResponse")
    public String serviceUnsubscribe(
        @WebParam(name = "operatorId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        int operatorId,
        @WebParam(name = "virtualBoxId", targetNamespace = "http://service.frontal.dematbox.sagemcom.com/")
        String virtualBoxId)
        throws SoapFaultException
    ;

}
