
package eu.agileeng.ws.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "FunctionalFault", targetNamespace = "http://service.dematbox.frontal.dematbox.sagemcom.com/")
public class SoapFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ComSagemcomDematboxFrontalDematboxServiceFaultBean faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public SoapFaultException(String message, ComSagemcomDematboxFrontalDematboxServiceFaultBean faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public SoapFaultException(String message, ComSagemcomDematboxFrontalDematboxServiceFaultBean faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: eu.agileeng.ws.client.ComSagemcomDematboxFrontalDematboxServiceFaultBean
     */
    public ComSagemcomDematboxFrontalDematboxServiceFaultBean getFaultInfo() {
        return faultInfo;
    }

}
