
package eu.agileeng.ws.client;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import eu.agileeng.accbureau.AEApp;
import eu.agileeng.util.AEStringUtil;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.0
 * 
 */
//@WebServiceClient(name = "WSFrontalImplService", targetNamespace = "http://serviceImpl.frontal.dematbox.sagemcom.com/", wsdlLocation = "file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/FrontalServiceAbstract.wsdl")
public class WSFrontalImplService
    extends Service
{

    private final static URL WSFRONTALIMPLSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(eu.agileeng.ws.client.WSFrontalImplService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = eu.agileeng.ws.client.WSFrontalImplService.class.getResource(".");
            url = new URL(baseUrl, "file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/FrontalServiceAbstract.wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'file:/C:/AgileEng/projects/Monentreprise/Java/accBureau/WebContent/wsdl/FrontalServiceAbstract.wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        WSFRONTALIMPLSERVICE_WSDL_LOCATION = url;
    }

    public WSFrontalImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WSFrontalImplService() {
        super(WSFRONTALIMPLSERVICE_WSDL_LOCATION, new QName("http://serviceImpl.frontal.dematbox.sagemcom.com/", "WSFrontalImplService"));
    }

    /**
     * 
     * @return
     *     returns IWSFrontal
     */
    @WebEndpoint(name = "WSFrontalImplPort")
    public IWSFrontal getWSFrontalImplPort() {
    	IWSFrontal port = super.getPort(new QName("http://serviceImpl.frontal.dematbox.sagemcom.com/", "WSFrontalImplPort"), IWSFrontal.class);
    	BindingProvider bindingProvider = (BindingProvider) port;

    	// set service endpoint address regards application's properties
    	String endpoint = AEApp.getInstance().getProperties().getProperty(AEApp.dematboxFrontalEndpoint);
    	if(AEStringUtil.isEmpty(endpoint)) {
    		endpoint = "https://dematbox.sagemcom.com/Frontal/WS/FrontalService";
    	}
    	bindingProvider.getRequestContext().put(
    			BindingProvider.ENDPOINT_ADDRESS_PROPERTY, 
    			endpoint);

    	return port;
    }

}
