Ext.define('MaParoisse.model.AccJournalItemExtended', {
	extend: 'MaParoisse.model.util.DomainRecord',
	
	fields: [{
		name: 'contributor',
		persist: false
	}, {
		name: 'contributorId',
		type: 'int',
		persist: false,
		mapping: 'contributor.id'
	}, {
		name: 'contributorFirstName',
		type: 'string',
		persist: false,
		mapping: 'contributor.employee.firstName'
	}, {
		name: 'contributorLastName',
		type: 'string',
		persist: false,
		mapping: 'contributor.employee.lastName'
	}, {
		name: 'contributorAddress',
		type: 'string',
		persist: false,
		mapping: 'contributor.employee.address.address'
	}, {
		name: 'contributorPostCode',
		type: 'string',
		persist: false,
		mapping: 'contributor.employee.address.postCode'
	}, {
		name: 'contributorTown',
		type: 'string',
		persist: false,
		mapping: 'contributor.employee.address.town'
	}, {
		name: 'accJournalItem',
		persist: false
	}, {
		name: 'ajiDate',
		type: 'date',
		dateFormat: 'd-m-Y',
		mapping: 'accJournalItem.date',
		persist: false
	},  {
		name: 'ajiDateCreation',
		type: 'date',
		dateFormat: 'd-m-Y',
		persist: false,
		mapping: 'accJournalItem.dateCreation'
	}, {
		name: 'ajiAccountIdentificationRuleId',
		type: 'int',
		persist: false,
		mapping: 'accJournalItem.accountIdentificationRuleId'
	}, {
		name: 'ajiJournalIdentificationRuleId',
		type: 'int',
		persist: false,
		mapping: 'accJournalItem.journalIdentificationRuleId'
	}, {
		name: 'ajiDtAmount',
		//type: 'string',
		type: 'number',
		persist: false,
		mapping: 'accJournalItem.dtAmount'
	}, {
		name: 'ajiCtAmount',
		//type: 'string',
		type: 'number',
		persist: false,
		mapping: 'accJournalItem.ctAmount'
	}, {
		name: 'ajiReference',
		persist: false,
		mapping: 'accJournalItem.reference'
	}, {
		name: 'ajiAccCode',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.accCode'
	}, {
		name: 'ajiAccName',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.accName'
	}, {
		name: 'ajiJournal',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.journal'
	}, {
		name: 'ajiAuxiliary',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.auxiliary'
	}, {
		name: 'ajiAccId',
		type: 'int',
		persist: false,
		mapping: 'accJournalItem.accId'
	}, {
		name: 'ajiCurrency',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.currency'
	}, {
		name: 'ajiDebit',
		type: 'boolean',
		persist: false,
		mapping: 'accJournalItem.debit'
	}, {
		name: 'ajiCredit',
		type: 'boolean',
		persist: false,
		mapping: 'accJournalItem.credit'
	}, {
		name: 'ajiEntryId',
		type: 'int',
		persist: false,
		mapping: 'accJournalItem.entryId'
	}, {
		name: 'ajiCodeQuete',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.codeQuete'
	}, {
		name: 'ajiDescription',
		type: 'string',
		persist: false,
		mapping: 'accJournalItem.description'
	}, {
		name: 'supplier',
		persist: false
	}, {
		name: 'supplierName',
		type: 'string',
		persist: false,
		mapping: 'supplier.name'
	}, {
		name: 'supplierId',
		type: 'string',
		persist: false,
		mapping: 'supplier.id'
	}, {
		name: 'openingBalance',
		persist: false,
		type: 'number'
	}, {
		name: 'closingBalance',
		persist: false,
		type: 'number'
	}, {
		name: 'date',
		type: 'date',
		dateFormat: 'd-m-Y'
	}, {
		name: 'dateCreation',
		type: 'date',
		dateFormat: 'd-m-Y'
	}, {
		name: 'entryGroupId',
		type: 'string',
		calculate: function(data){
			if(data.ajiEntryId > 0){
				var dateString = Ext.Date.format(data.ajiDate, 'Ymd');
				return dateString + data.ajiEntryId.toString();
			} else if (data.ajiEntryId == 0){
				return 'b0';
			} else {
				return 'a' + Math.abs(data.ajiEntryId);
			}
		}
	}, {
		name: 'attachmentName',
		type: 'string',
		persist: 'false'
	}, {
		name: 'attachmentRemoteName',
		type: 'string',
		persist: 'false'
	}, {
		name: 'attachmentId',
		type: 'int',
		persist: 'false'
	}, {
		name: 'ajiBatchId',
		type: 'int',
		//persist: false,
		mapping: 'accJournalItem.batchId'
	}, {
		name: 'ajiTally',
		type: 'boolean',
		mapping: 'accJournalItem.tally'
	}]
});