Ext.define('MaParoisse.model.AccJournalItem', {
	extend: 'MaParoisse.model.util.DomainRecord',
	fields:[{
		name: 'date',
		type: 'date',
		dateFormat: 'd-m-Y'
	}, {
		name: 'dateCreation',
		type: 'date',
		dateFormat: 'd-m-Y'
	}, {
		name: 'accountIdentificationRuleId',
		type: 'int'
	}, {
		name: 'journalIdentificationRuleId',
		type: 'int'
	}, {
		name: 'dtAmount',
		type: 'string'
	}, {
		name: 'ctAmount',
		type: 'string'
	}, {
		name: 'reference'
	}, {
		name: 'accCode',
		type: 'string'
	}, {
		name: 'journal',
		type: 'string'
	}, {
		name: 'auxiliary',
		type: 'string'
	}, {
		name: 'accId',
		type: 'int'
	}, {
		name: 'currency',
		type: 'string'
	}, {
		name: 'debit',
		type: 'boolean'
	}, {
		name: 'credit',
		type: 'boolean'
	}, {
		name: 'entryId',
		type: 'int'
	}, {
		name: 'codeQuete',
		type: 'string'
	}, {
		name: 'batchId',
		type: 'int'
	}, {
		name: 'tally',
		type: 'boolean'
	}]
});